import 'package:flutter/material.dart';
import 'package:hale_app/src/utils/constants.dart';

class TermsAndConditionsPage extends StatefulWidget {
  const TermsAndConditionsPage({Key? key}) : super(key: key);

  static String routeName = "terms_and_conditions_page";

  @override
  State<TermsAndConditionsPage> createState() => _TermsAndConditionsPageState();
}

class _TermsAndConditionsPageState extends State<TermsAndConditionsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text(
            "T&C",
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          ),
          centerTitle: true,
          elevation: 0.0,
          iconTheme: const IconThemeData(color: Colors.white),
          backgroundColor: Constants.blueGeneric,
        ),
        body: Padding(
          padding: const EdgeInsets.all(20.0),
          child: GestureDetector(
            onTap: () {
              FocusScope.of(context).unfocus();
            },
            child: ListView(
              physics: const ClampingScrollPhysics(),
              children: [
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: const [
                    Text(
                      'Terminos y condicions',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                        color: Color.fromRGBO(0, 34, 91, 1),
                      ),
                    ),
                  ],
                ),
                textWidget(
                    text:
                        'POR MEDIO DE ESTA AVISO LEGAL, CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, INFORMAN A LOS USUARIOS DE LAS PÁGINAS DE CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., (EN ADELANTE LOS “USUARIOS”), QUE A TRAVÉS DE ÉSTAS PONE A SU DISPOSICIÓN DISPOSITIVOS TÉCNICOS DE ENLACE (TALES COMO, ENTRE OTROS, LINKS, BANNERS, BOTONES), DIRECTORIOS Y HERRAMIENTAS DE BÚSQUEDA QUE LES PERMITEN ACCEDER A PÁGINAS WEB PERTENECIENTES A TERCEROS (EN ADELANTE LOS “SITIOS ENLAZADOS”).'),
                textWidget(
                    text:
                        'LA INSTALACIÓN DE ESTOS ENLACES EN LAS PÁGINAS DE CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V, SUS SUBSIDIARIAS Y/O AFILIADAS SE LIMITA A FACILITAR A LOS USUARIOS LA BÚSQUEDA DE, Y ACCESO, A LA INFORMACIÓN DISPONIBLE DE LOS SITIOS ENLAZADOS EN INTERNET, Y NO PRESUPONE QUE EXISTA NINGUNA CLASE DE VÍNCULO O ASOCIACIÓN ENTRE CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, Y LOS OPERADORES DE LOS SITIOS ENLAZADOS.'),
                textWidget(
                    text:
                        'LA UTILIZACIÓN DE LAS PÁGINAS LE ATRIBUYE A UD. LA CONDICIÓN DE USUARIO DE LAS PÁGINAS (EN ADELANTE, EL “USUARIO”) E IMPLICA LA ACEPTACIÓN PLENA Y SIN RESERVAS DE TODAS Y CADA UNA DE LAS DISPOSICIONES INCLUIDAS EN ESTE AVISO LEGAL EN LA VERSIÓN PUBLICADA POR CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V. EN EL MOMENTO MISMO EN QUE EL USUARIO ACCEDA A LAS PÁGINAS. EN CONSECUENCIA, EL USUARIO DEBE LEER EL PRESENTE AVISO LEGAL EN CADA UNA DE LAS OCASIONES EN QUE UTILICE LAS PÁGINAS, YA QUE PUEDESUFRIR MODIFICACIONES.'),
                textWidget(
                    text:
                        'CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS NO CONTROLAN, APRUEBAN NI HACEN PROPIOS LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS. EL USUARIO, POR LO TANTO, DEBE EXTREMAR LA PRUDENCIA EN LA VALORACIÓN Y UTILIZACIÓN DE LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS. CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN NI ASUMEN RESPONSABILIDAD ALGUNA POR LOS DAÑOS Y PERJUICIOS DE TODA CLASE QUE PUEDAN CAUSARSE POR:'),
                textWidget(
                    text:
                        'A) EL FUNCIONAMIENTO, DISPONIBILIDAD, ACCESIBILIDAD O CONTINUIDAD DE LOS SITIOS ENLAZADOS. B) EL MANTENIMIENTO DE LOS SERVICIOS, INFORMACIÓN, DATOS, ARCHIVOS, PRODUCTOS Y CUALQUIER CLASE DE MATERIAL EXISTENTE EN LOS SITIOS ENLAZADOS C) LAS OBLIGACIONES Y OFERTAS EXISTENTES EN LOS SITIOS ENLAZADOS CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE  C.V. PODRÁ EN CUALQUIER MOMENTO NEGAR, SUSPENDER O DAR POR TERMINADO EL ACCESO O EL USO DEL USUARIO A LAS PÁGINAS, A CUALQUIER SERVICIO Y PRODUCTO, O CUALQUIER PARTE DE LOS MISMOS, A SOLA DISCRECIÓN DE GRUPO MACRO, SIN NECESIDAD DE PREVIO AVISO, SIN LIMITACIÓN ALGUNA, Y POR CUALQUIER RAZÓN.'),
                textWidget(
                    text:
                        'POR LO ANTERIOR, GRUPO MACRO NO GARANTIZA LA UTILIDAD, DISPONIBILIDAD Y CONTINUIDAD DEL FUNCIONAMIENTO DE LAS PÁGINAS ASÍ COMO DE LOS SERVICIOS Y PRODUCTOS PARA LA REALIZACIÓN DE ALGUNA ACTIVIDAD EN ESPECÍFICO, O SU INFALIBILIDAD. MEDIANTE LA UTILIZACIÓN DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS, NO GARANTIZAN QUE LOS SITIOS ENLAZADOS O LA INFORMACIÓN PROPORCIONADA POR TERCEROS, SEAN ÚTILES PARA LA REALIZACIÓN DE NINGUNA ACTIVIDAD EN PARTICULAR. MEDIANTE EL USO DE ESTA PÁGINA, EL USUARIO RECONOCE Y ACEPTA QUE CELULARES Y ACCESORIOS DEL SURESTE, S.A. DE C.V., SUS SUBSIDIARIAS Y/O AFILIADAS QUEDAN EXCLUIDAS DE CUALQUIER RESPONSABILIDAD POR LOS DAÑOS Y PERJUICIOS QUE PUDIERAN HABER SIDO CAUSADOS POR LA VERACIDAD DE LA INFORMACIÓN O CALIDAD DE SERVICIOS CONTENIDOS U OFRECIDOS POR TERCEROS O QUE SE ENCUENTRE EN LOS SITIOS ENLAZADOS, O LOS QUE SURJAN CON RELACIÓN A ESTE SITIO. TANTO EL ACCESO A ESTA PÁGINA COMO EL USO QUE PUEDA HACERSE DE LA INFORMACIÓN CONTENIDA EN EL MISMO SON EXCLUSIVA RESPONSABILIDAD DEL USUARIO.'),
                textWidget(
                    text:
                        'ALGUNOS SERVICIOS Y PRODUCTOS PUESTOS A DISPOSICIÓN DEL USUARIO A TRAVÉS DE LAS PÁGINAS PODRÁN REQUERIR DE CLAVES O CONTRASEÑAS (“PASSWORDS”), A FIN DE VERIFICAR LA IDENTIDAD DEL USUARIO. EL USUARIO ESTÁ DE ACUERDO EN QUE CUALQUIER OPERACIÓN CORRECTAMENTE IDENTIFICADA CON DICHOS PASSWORDS SERÁ CONSIDERADAS COMO VÁLIDAMENTE REALIZADAS POR EL USUARIO. POR LO ANTERIOR, EL USUARIO SERÁ EL ÚNICO RESPONSABLE DE MANTENER LA CONFIDENCIALIDAD DE DICHOS PASSWORDS, SIN IMPORTAR SI ÉSTOS FUERON PROPORCIONADOS POR GRUPO MACRO O SELECCIONADOS POR EL USUARIO DIRECTAMENTE. CUALQUIER INFORMACIÓN ENVIADA POR LOS USUARIOS Y QUE SEA RECIBIDA EN LAS PÁGINAS, TAL COMO COMENTARIOS, SUGERENCIAS O IDEAS, SE CONSIDERARÁ CEDIDA A GRUPO MACRO A TÍTULO GRATUITO, Y EL USUARIO QUE LA ENVÍE ACEPTA IMPLÍCITAMENTE QUE NO TIENE CARÁCTER DE CONFIDENCIAL.'),
                textWidget(
                    text:
                        'ALGUNOS SERVICIOS Y PRODUCTOS PUESTOS A DISPOSICIÓN DEL USUARIO A TRAVÉS DE LAS PÁGINAS PODRÁN REQUERIR DE CLAVES O CONTRASEÑAS (“PASSWORDS”), A FIN DE VERIFICAR LA IDENTIDAD DEL USUARIO. EL USUARIO ESTÁ DE ACUERDO EN QUE CUALQUIER OPERACIÓN CORRECTAMENTE IDENTIFICADA CON DICHOS PASSWORDS SERÁ CONSIDERADAS COMO VÁLIDAMENTE REALIZADAS POR EL USUARIO. POR LO ANTERIOR, EL USUARIO SERÁ EL ÚNICO RESPONSABLE DE MANTENER LA CONFIDENCIALIDAD DE DICHOS PASSWORDS, SIN IMPORTAR SI ÉSTOS FUERON PROPORCIONADOS POR GRUPO MACRO O SELECCIONADOS POR EL USUARIO DIRECTAMENTE. CUALQUIER INFORMACIÓN ENVIADA POR LOS USUARIOS Y QUE SEA RECIBIDA EN LAS PÁGINAS, TAL COMO COMENTARIOS, SUGERENCIAS O IDEAS, SE CONSIDERARÁ CEDIDA A GRUPO MACRO A TÍTULO GRATUITO, Y EL USUARIO QUE LA ENVÍE ACEPTA IMPLÍCITAMENTE QUE NO TIENE CARÁCTER DE CONFIDENCIAL.'),
              ],
            ),
          ),
        ));
  }

  Widget textWidget({required String text}) => Column(
        children: [
          const SizedBox(height: 15),
          Text(
            text,
            textAlign: TextAlign.justify,
            style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
          ),
          const SizedBox(height: 15),
        ],
      );
}
