
INSERT INTO stateinegi(clave,valor,country) VALUES ('AGS','Aguascalientes','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('BC','Baja California','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('BCS','Baja California Sur','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('CHI','Chihuahua','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('CHS','Chiapas','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('CMP','Campeche','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('CMX','Ciudad De Mexico','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('COA','Coahuila','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('COL','Colima','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('DGO','Durango','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('GRO','Guerrero','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('GTO','Guanajuato','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('HGO','Hidalgo','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('JAL','Jalisco','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('MCH','Michoacan','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('MEX','Estado De Mexico','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('MOR','Morelos','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('NAY','Nayarit','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('NL','Nuevo Leon','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('OAX','Oaxaca','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('PUE','Puebla','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('QR','Quintana Roo','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('QRO','Queretaro','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('SIN','Sinaloa','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('SLP','San Luis Potosi','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('SON','Sonora','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('TAB','Tabasco','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('TLX','Tlaxcala','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('TMS','Tamaulipas','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('VER','Veracruz','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('YUC','Yucatan','MX');
INSERT INTO stateinegi(clave,valor,country) VALUES ('ZAC','Zacatecas','MX');
